### PR TITLE
Adding table of content, list of DV researchers and some other papers

### PR DESCRIPTION
**Pull request by alireza-karimi**
Hi,

Thanks for creating the great repo on data valuation. I wanted to contribute and add some other stuffs:
* A nice table of content :d -> I found it hard myself to see what's included in the repo. Hope the table of content can help.
* A list of researchers contributing to the field of data valuation -> When I was exploring different papers, I was looking for a list of researchers in the field to follow but I could not find a good list. So I created one and would be happy to share with the community.
* I have also added some other papers that I found on the topic.

Please let me know if there are anythings needed to be fixed.

Bests,
Alireza

### CODE REVIEW

**Comment by alireza-karimi** [comment]
@daviddao Let me know if there are any other things that I can help on.

**Comment by daviddao** [comment]
Love this! Maybe for the h-index of researchers, let's add a timestamp as well, otherwise I think it can be quite outdated very fast. This is wonderful!

**Comment by daviddao** [comment]
However, I'll merge it in for now, and then we can adjust this in a next pull request! Super cool!

**Comment by alireza-karimi** [comment]
Sure, We can somehow make h-index (and possibly number of papers citations) dynamic, or add an update date as you said

**Pull request merged**
